export const FACTORY_VAULT_ID =
  'CDKFHFJIET3A73A2YN4KV7NSV32S6YGQMUFH3DNJXLBWL4SKEGVRNFKI';

export const SERVER_ENDPOINT = 'http://localhost:4000/api/v1/';

// blend auto compaund fixed
const SUPER_USDC = 'CBYQ6LIUFBXPKN57AMP6YBPX4EKBSGPLZBO4CN4R5HYJXY57M3MQRRGQ'; // = blend auto compund fixed
const SUPER_XLM = 'CCCXWCYZU4QNUIIPTMWV2KFDRAREW2O5FSXL3L24L7FWXSQCDKTRFUPW'; // = BLEND AUTO COMPAUND YIELD BOX
const super_eurc = 'CBYTOTXFO5IVMH5N2ZRR376IRTKS5ZO3QBYUMNBMQFLAOXCAQC6DBDFK';
